# Generated by Django 5.0.4 on 2024-04-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_callhistory_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callhistory',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
