version: '3.8'
services:
    db:
        image: postgres:13
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            POSTGRES_DB: callshistorydb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: helloworld
        expose:
            - '5432'
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        environment:
            - PYTHONPATH=/code
            - DJANGO_SETTINGS_MODULE=callshistory.settings
        working_dir: /code
        volumes:
            - .:/code
        ports:
            - '8000:8000'
        depends_on:
            - db
volumes:
    postgres_data:
